// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtHHGW5deb-llC80X35BA0JLE6og72uaU',
    appId: '1:603251372800:android:8678bc086d026d1aeb79e5',
    messagingSenderId: '603251372800',
    projectId: 'pgas-22c9e',
    storageBucket: 'pgas-22c9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRGQbx-o9T8Qb9TMSny8UaWBgi76AW1I0',
    appId: '1:603251372800:ios:666a18541a317d7ceb79e5',
    messagingSenderId: '603251372800',
    projectId: 'pgas-22c9e',
    storageBucket: 'pgas-22c9e.firebasestorage.app',
    iosBundleId: 'com.example.pgas',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4xj6s-e_q_G9NA-mCsZH91TyMZUEm4J0',
    appId: '1:603251372800:web:b66858d27d02f141eb79e5',
    messagingSenderId: '603251372800',
    projectId: 'pgas-22c9e',
    authDomain: 'pgas-22c9e.firebaseapp.com',
    storageBucket: 'pgas-22c9e.firebasestorage.app',
    measurementId: 'G-GFBPZ10XXT',
  );

}